### ISSUE TITLE
Rework/renaming of "Competition" and "Arena" classes

### ISSUE THREAD

**Issue by RednedEpic** [BattlePlugins/BattleArena-4.0#1]
In the legacy version of BattleArena, each custom "arena" extends a class called `Arena`, which allows for plugins to create more extensive games (such as CTF and paintball), however the naming of that is somewhat deceptive. 

In most cases, people think of an arena as a place where the game takes place. Contrary to that in BattleArena, each "arena" represents a game instead (see [SpleefArena](https://github.com/BattlePlugins/ArenaSpleef/blob/master/src/java/mc/arena/spleef/SpleefArena.java), [CTFArena](https://github.com/BattlePlugins/ArenaCTF/blob/master/src/java/mc/alk/ctf/CTFArena.java)). Physical arenas are represented by either Matches or Events, which extend a base Competition class. This may be in-part due to the fact that all "arenas" at one point were just Matches, but with the addition of events, abstraction was added and Competition became the base class. However after some more discussion on Discord, we hit a bit of a roadblock about what we should do in this scenario. The first idea suggested was just flipping Arena and Competition, but that also brings into questions where the derivatives of the existing Competition class should go.

This also puts a broader question into light, about what entitles an Event or a Match (deriative of Competition), and where their data would lie in this. The current system allows for games to define this on a per-arena basis (albeit the only way to achieve this is to override parameters in arenas.yml), meaning myarena1 could be a Match whilst myarena2 is an Event, both for the same game. At least in my opinion, there is very little that differs between and a Match and an Event, and the only difference I've noticed is that events can be started by server operators, unlike matches where they're "started" when a player joins them. This also raises the question where a Tourney class would set, and a potential Medley class as well. 

Ultimately, this is a much deeper issue, and will require quite a bit more thought. If anyone has any ideas, please feel free to chime in.

**Comment by Europia79** [comment]
I'm thinking of Arena as a definition with rules, victory conditions, a location for one world, a schematic for multi-worlds, & something to facilitate multi-server if that's configured.  Then, for the most part, it had a good seem with custom plugins to extend it and override the rules for customization... except the onStart() and other overridable methods... while convenient, they might be out of place, conceptually...

...since it's the Matches that Start() and End()...  And I think of a Match as an Arena Instance with Players and everything that goes along with Arena:  Possible Timer and/or VictoryConditions and other rules & events.

Then Competition further complicates things.  While I think of a Match as one game with potentially multiple rounds... I think of a Competition as a series of Matches... like in a playoff bracket.  And there are many different ways to implement and/or configure Playoffs & Brackets.

You can have double elimination.

You can have two conferences that meet at the end for the Championship game finale.

Hope this helps.  Lemme know.

**Comment by Europia79** [comment]
So... if we go that route, as far as the relationship between Arena & Match...  The question arises if we want to do inheritance or composition... where we pass the Arena (rule-set) to the Match with the list of Teams & Players.

I think we should just compose them together:  Match HAS An Arena... so the Arena object and all other dependencies (like Teams, Players, etc) are passed to it.

And when Match Starts & Ends... we use the Arena object to call onStart() & onEnd() (etc).

Slightly awkward... but i think it's better than inheritance in this situation.

**Comment by RednedEpic** [comment]
> I'm thinking of Arena as a definition with rules, victory conditions, a location for one world, a schematic for multi-worlds, & something to facilitate multi-server if that's configured. Then, for the most part, it had a good seam with custom plugins to extend it and override the rules for customization... except the onStart() and other overridable methods... while convenient, they might be out of place, conceptually...
> 
> ...since it's the Matches that Start() and End()... And I think of a Match as an Arena Instance with Players and everything that goes along with Arena: Possible Timer and/or VictoryConditions and other rules & events.
> 
> Then Competition further complicates things. While I think of a Match as one game with potentially multiple rounds... I think of a Competition as a series of Matches... like in a playoff bracket. And there are many different ways to implement and/or configure Playoffs & Brackets.
> 
> You can have double elimination.
> 
> You can have two conferences that meet at the end for the Championship game finale.
> 
> Hope this helps. Lemme know.

I've finally had some time to sit down and look at this in more detail, and I think I'm able to understand the thinking behind this a bit more. Match represent the ongoing game while Arena contains most of the game definition/rules.

I think ultimately, having Match as the base class, with Events and Tourneys just being Matches as well or being subclasses would be the ideal solution here. Competitions, if we decide to add them, would make more sense if they contained multiple Matches. Tourneys and a Medley gamemode could be derivatives of this.

> So... if we go that route, as far as the relationship between Arena & Match... The question arises if we want to do inheritance or composition... where we pass the Arena (rule-set) to the Match with the list of Teams & Players.
> 
> I think we should just compose them together: Match HAS An Arena... so the Arena object and all other dependencies (like Teams, Players, etc) are passed to the Match constructor.
> 
> And when Match Starts & Ends... we use the Arena object to call onStart() & onEnd() (etc).
> 
> Slightly awkward... but i think it's better than inheritance in this situation.

I definitely agree, composition is the way to go. Match should handle most all the actual "match" information, such as what player is on what team and how many times a team has captured the flag; meanwhile Arena should contain most of the game rules, logic and how the game ultimately, will work.

**Comment by Europia79** [comment]
If there's an inheritance relationship between Competition & Tournament, then what's the difference between a Competition & a Tournament ?  And what similarities do they share that justifies the relationship "Tournament IS A Competition" (extends) ?  ...Multiple games per Match ?  ...Just making sure I understand this correctly.

Also... the new Arenas should have a configuration & class member for the number of Rounds... Then the Match object can get this information and use it to for multiple Rounds (if configured).  This really only makes sense if Respawn is OFF.  If Respawn is ON... then it makes more sense just to configure one Round, imo.

**Comment by RednedEpic** [comment]
> If there's an inheritance relationship between Competition & Tournament, then what's the difference between a Competition & a Tournament ? And what similarities do they share that justifies the relationship "Tournament IS A Competition" (extends) ? ...Multiple games per Match ? ...Just making sure I understand this correctly.

Tournament would (or could) contain multiple rounds at once, like brackets. The game would continue until there are two people or teams left against each other. Tournament would be a Competition because it contains multiple Matches, and in most scenarios, simultaneous Matches. 

Medley would also be a Competition, but not be the same as a Tournament per se, since it's just a grouping of different Matches/Arenas altogether. Medleys would also not be running simultaneous Matches, while Tournaments would and Medleys would be groupings of multiple different games altogether, while Tournaments would just be a tournament for the game itself. However, both would share the same methods in Competition, to divvy out the rewards after all the games/Matches are complete. 

> 
> Also... the new Arenas should have a configuration & class member for the number of Rounds... Then the Match object can get this information and use it to for multiple Rounds (if configured). This really only makes sense if Respawn is OFF. If Respawn is ON... then it makes more sense just to configure one Round, imo.

Yeah, this is definitely something I intend to add. However, I feel like it may come up as a question about what differentiates a Match with multiple rounds and a Competition. From my thinking, a Competition is just a group of Matches, whether they're from the same Arena or not, and a Match with multiple rounds is the _same_ Match, with most information from the previous Match carrying over, with the exception of a few (e.g. lives). Final statistics would be determined at the end of each round, meanwhile in Competitions with multiple Matches, this information would be determined at the end of each individual Match.

However, in Medleys and Tournaments, server owners may want to disable individual tracking and just have an individual statistic for the Medley itself. One example of this would by Hypixel's party games. They have a group of different games, but the end statistics are their own separate thing and rewards are like "party games rewards." Matches then in these Medley competitions could also have a set amount of rounds as well.

Hopefully this makes a bit more sense.
